### PR TITLE
Fix selector matching

### LINKED ISSUE #22: May need to aggressively selector-match exact sequence matches as well
The PR in #18 may not be sufficient. We may need to agressively test for selector matches after filtering for sequence matches. Otherwise, we may falsely reject a partial match. 

Let's have a hangout about this.

### PR DESCRIPTION
**Pull request by sccolbert**
This updates the selector matching algorithm to ensure both exact and partial matches *also* match their selector *before* taking any further action or stopping event propagation.

This also changes handler behavior in that handlers are now void functions instead of returning a boolean. The previous behavior allowed multiple matching handlers to be invoked in sequence, provided the earlier handlers returned `false`. This is no longer possible. A matched handler is now considered to *always handle the match*, which is behavior we saw in practice. This assumption allows many more optimization for dispatching. For example, a separate filter/sort step is not required, as best-match finding can performed inline with match-validity testing. This cuts out a ton of work and allocations.

This fixes #22.

### CODE REVIEW

**Comment by dwillmer** [comment]
:+1:

File: src/manager.ts [hunk 1]
```diff
@@ -391,83 +366,93 @@ function matchSequence(exbSeq: string[], keySeq: string[]): SequenceMatch {
...
+    if (match === SequenceMatch.Partial) {
+      if (!partial && targetDistance(exb.selector, event) !== -1) {
+        partial = true;
       }
+      continue;
     }
-    if (target === event.currentTarget) {
-      return;
+
+    // Otherwise, it's an exact match. Update the best match if the
```
Comment (blink1073) [inline src/manager.ts]: This comment is misleading because you don't state in the previous comment that we always `continue` if there is a partial match.
